### ISSUE TITLE
Bad sorting techs in levels

### ISSUE THREAD

**Issue by belozer** [gulp-bem/gulp-bem-src#13]
```js
const builder = Builder({
    levels: [
        'bem/libs/bem-core/common.blocks',
        'bem/libs/bem-core/desktop.blocks',
        'bem/libs/bem-components/common.blocks',
        'bem/libs/bem-components/desktop.blocks',
        'bem/libs/bem-components/design/common.blocks',
        'bem/libs/bem-components/design/desktop.blocks',
        'bem/libs/bem-forms/common.blocks'
    ],
    techMap: {
        js: ['vanilla.js', 'source.js', 'browser.js', 'js'],
        css: ['styl', 'post.css', 'css']
    }
});
```

Exapmle block: __checkbox__

In level 'bem-forms' tech.name __checkbox.browser.js__
In level 'bem-components' tech.name __checkbox.js__

Durning build __checkbox.js__ added after __checkbox.browser.js__

**Comment by tadatuta** [comment]
@belozer not sure if I got it right but an order in techMap array should be significant and you may try to toggle `js` and `browser.js` in it to solve this issue.

Please tell if it helps.

**Comment by belozer** [comment]
@tadatuta this is a working method. In my current gulpfile swapped `js` and `browser.js`

`js: ['js', 'vanilla.js', 'source.js', 'browser.js'],`

but this is a bug :bug: ;)

**Comment by tadatuta** [comment]
can't understand why it's a bug if it works? :)

**Comment by skad0** [comment]
> can't understand why it's a bug if it works? :)

looks like unexpected behaviour, isn't it?

**Comment by qfox** [comment]
@tadatuta What should be the right order?

```
- l1/b1.t1
- l1/b1.t2
- l2/b1.t1
- l2/b1.t2
```

vs

```
- l1/b1.t1
- l2/b1.t1
- l1/b1.t2
- l2/b1.t2
```

We need to add a test case here and fix the bug if it exists.
